"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pages = void 0;
exports.pages = [
    // Top Level Pages
    {
        id: 'page-home',
        title: 'Ana Sayfa',
        slug: '/',
        status: 'published',
        seo: {
            title: 'Aluplan Digital - AEC Çözümleri',
            description: 'AEC profesyonelleri için en gelişmiş dijital çözümler ve uzman desteği.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:00:00.000Z',
        content: [],
    },
    {
        id: 'page-solutions',
        title: 'Çözümler',
        slug: '/solutions',
        status: 'published',
        seo: {
            title: 'Çözümlerimiz | Aluplan Digital',
            description: 'Sektörünüz ne olursa olsun, projenizin her aşaması için güçlü ve esnek bir çözümümüz var.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:01:00.000Z',
        content: [],
    },
    {
        id: 'page-products',
        title: 'Ürünler',
        slug: '/products',
        status: 'published',
        seo: {
            title: 'Ürünlerimiz | Aluplan Digital',
            description: 'İhtiyaçlarınıza özel olarak tasarlanmış, sektör lideri Allplan ve iş ortağı ürünlerini keşfedin.',
        },
        authorId: 'usr-002',
        lastUpdated: '2024-07-31T10:02:00.000Z',
        content: [],
    },
    {
        id: 'page-case-studies',
        title: 'Başarı Hikayeleri',
        slug: '/case-studies',
        status: 'published',
        seo: {
            title: 'Başarı Hikayeleri | Aluplan Digital',
            description: 'Allplan çözümlerinin, Türkiye ve dünyadan prestijli projelerde nasıl fark yarattığını keşfedin.',
        },
        authorId: 'usr-002',
        lastUpdated: '2024-07-31T10:03:00.000Z',
        content: [],
    },
    {
        id: 'page-contact',
        title: 'İletişim',
        slug: '/contact',
        status: 'published',
        seo: {
            title: 'İletişim | Aluplan Digital',
            description: 'Uzman ekibimizle tanışın ve dijital dönüşüm yolculuğunuzda size nasıl yardımcı olabileceğimizi öğrenin.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:04:00.000Z',
        content: [],
    },
    {
        id: 'page-downloads',
        title: 'İndirme Merkezi & Destek',
        slug: '/downloads',
        status: 'published',
        seo: {
            title: 'İndirme Merkezi & Destek | Aluplan Digital',
            description: 'Gerekli tüm kaynaklara, dokümanlara ve destek kanallarına buradan ulaşın.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:05:00.000Z',
        content: [],
    },
    {
        id: 'page-education',
        title: 'Eğitim & Destek',
        slug: '/education',
        status: 'published',
        seo: {
            title: 'Eğitim & Destek | Aluplan Digital',
            description: 'Bilgi birikiminizi artırın, kaynaklarımıza erişin ve ihtiyacınız olan desteği alın.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:06:00.000Z',
        content: [],
    },
    // Education Subpages
    {
        id: 'page-education-certification',
        title: 'Sertifika Sorgulama',
        slug: '/education/certification',
        status: 'published',
        seo: {
            title: 'Sertifika Sorgulama | Aluplan Digital',
            description: 'Aluplan tarafından verilen sertifikaların geçerliliğini anında doğrulayın.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:07:00.000Z',
        content: [],
    },
    {
        id: 'page-education-training',
        title: 'Eğitim & Danışmanlık',
        slug: '/education/training',
        status: 'published',
        seo: {
            title: 'Eğitim & Danışmanlık | Aluplan Digital',
            description: 'Allplan yetkinliğinizi en üst düzeye çıkarmak için tasarlanmış eğitim programları.',
        },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:08:00.000Z',
        content: [],
    },
    // Products Subpages
    {
        id: 'page-products-allplan',
        title: 'Allplan Ürün Ailesi',
        slug: '/products/allplan',
        status: 'published',
        seo: { title: 'Allplan Ürün Ailesi | Aluplan Digital', description: 'Tasarım, mühendislik ve inşaat için her ihtiyaca yönelik kapsamlı BIM çözümleri.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:09:00.000Z',
        content: [],
    },
    ...['basic', 'concept', 'professional', 'ultimate', 'civil', 'precast'].map(v => ({
        id: `page-products-allplan-${v}`,
        title: `Allplan ${v.charAt(0).toUpperCase() + v.slice(1)}`,
        slug: `/products/allplan/${v}`,
        status: 'published',
        seo: { title: `Allplan ${v.charAt(0).toUpperCase() + v.slice(1)} | Aluplan Digital`, description: `Allplan ${v} detayları.` },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:10:00.000Z',
        content: [],
    })),
    {
        id: 'page-products-building-infrastructure',
        title: 'Bina ve Altyapı Yazılımları',
        slug: '/products/building-infrastructure',
        status: 'published',
        seo: { title: 'Bina ve Altyapı Yazılımları | Aluplan Digital', description: 'Bina ve altyapı projeleriniz için güçlü, entegre ve özel yazılım çözümleri.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:11:00.000Z',
        content: [],
    },
    ...['allplan-aec', 'allplan-bridge', 'ax3000'].map(v => ({
        id: `page-products-building-infrastructure-${v}`,
        title: v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
        slug: `/products/building-infrastructure/${v}`,
        status: 'published',
        seo: { title: `${v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} | Aluplan Digital`, description: `${v} detayları.` },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:12:00.000Z',
        content: [],
    })),
    {
        id: 'page-products-collaboration',
        title: 'İşbirliği Yazılımları',
        slug: '/products/collaboration',
        status: 'published',
        seo: { title: 'İşbirliği Yazılımları | Aluplan Digital', description: 'Proje paydaşlarınızı tek bir platformda birleştiren çözümler.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:13:00.000Z',
        content: [],
    },
    {
        id: 'page-products-collaboration-bimplus',
        title: 'Bimplus',
        slug: '/products/collaboration/bimplus',
        status: 'published',
        seo: { title: 'Bimplus | Aluplan Digital', description: 'Disiplinlerarası işbirliği için açık BIM platformu.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:14:00.000Z',
        content: [],
    },
    {
        id: 'page-products-construction-planning',
        title: 'İnşaat Planlama Yazılımları',
        slug: '/products/construction-planning',
        status: 'published',
        seo: { title: 'İnşaat Planlama Yazılımları | Aluplan Digital', description: 'İnşaat süreçlerinizi optimize eden özel yazılımlar.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:15:00.000Z',
        content: [],
    },
    ...['sds2', 'tim'].map(v => ({
        id: `page-products-construction-planning-${v}`,
        title: v.toUpperCase(),
        slug: `/products/construction-planning/${v}`,
        status: 'published',
        seo: { title: `${v.toUpperCase()} | Aluplan Digital`, description: `${v} detayları.` },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:16:00.000Z',
        content: [],
    })),
    // Solutions Subpages
    {
        id: 'page-solutions-building-design',
        title: 'Bina Tasarımı Çözümleri',
        slug: '/solutions/building-design',
        status: 'published',
        seo: { title: 'Bina Tasarımı Çözümleri | Aluplan Digital', description: 'Mimari, strüktürel mühendislik ve MEP için entegre BIM çözümleri.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:17:00.000Z',
        content: [],
    },
    ...['architecture', 'structural-engineering', 'mep'].map(v => ({
        id: `page-solutions-building-design-${v}`,
        title: v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
        slug: `/solutions/building-design/${v}`,
        status: 'published',
        seo: { title: `${v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} | Aluplan Digital`, description: `${v} detayları.` },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:18:00.000Z',
        content: [],
    })),
    {
        id: 'page-solutions-infrastructure-design',
        title: 'Altyapı Tasarımı Çözümleri',
        slug: '/solutions/infrastructure-design',
        status: 'published',
        seo: { title: 'Altyapı Tasarımı Çözümleri | Aluplan Digital', description: 'Yol, köprü, demiryolu ve genel altyapı projeleriniz için güçlü BIM çözümleri.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:19:00.000Z',
        content: [],
    },
    ...['infrastructure-engineering', 'road-railway-design', 'bridge-design'].map(v => ({
        id: `page-solutions-infrastructure-design-${v}`,
        title: v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
        slug: `/solutions/infrastructure-design/${v}`,
        status: 'published',
        seo: { title: `${v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} | Aluplan Digital`, description: `${v} detayları.` },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:20:00.000Z',
        content: [],
    })),
    {
        id: 'page-solutions-construction-planning',
        title: 'İnşaat Planlaması Çözümleri',
        slug: '/solutions/construction-planning',
        status: 'published',
        seo: { title: 'İnşaat Planlaması Çözümleri | Aluplan Digital', description: 'Prefabrik üretimden şantiye yönetimine kadar inşaat süreçlerinizi optimize edin.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:21:00.000Z',
        content: [],
    },
    ...['precast-production', 'steel-detailing', 'site-planning'].map(v => ({
        id: `page-solutions-construction-planning-${v}`,
        title: v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
        slug: `/solutions/construction-planning/${v}`,
        status: 'published',
        seo: { title: `${v.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} | Aluplan Digital`, description: `${v} detayları.` },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:22:00.000Z',
        content: [],
    })),
    {
        id: 'page-solutions-add-on-modules',
        title: 'Ek Modüller',
        slug: '/solutions/add-on-modules',
        status: 'published',
        seo: { title: 'Ek Modüller | Aluplan Digital', description: 'Allplan Exchange, Workgroup, Share ve Lisans Sunucusu gibi modüllerle işlevselliği artırın.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:23:00.000Z',
        content: [],
    },
    {
        id: 'page-solutions-collaboration',
        title: 'İşbirliği Çözümleri',
        slug: '/solutions/collaboration',
        status: 'published',
        seo: { title: 'İşbirliği Çözümleri | Aluplan Digital', description: 'Proje ve ekipleriniz için entegre işbirliği ve yönetim araçları.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:24:00.000Z',
        content: [],
    },
    {
        id: 'page-solutions-plugins',
        title: 'Eklentiler',
        slug: '/solutions/plugins',
        status: 'published',
        seo: { title: 'Eklentiler | Aluplan Digital', description: "Allplan'in yeteneklerini genişleten ve iş akışlarınızı özelleştiren güçlü eklentiler." },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:25:00.000Z',
        content: [],
    },
    // Legal Pages
    {
        id: 'page-privacy',
        title: 'Gizlilik Politikası',
        slug: '/privacy',
        status: 'published',
        seo: { title: 'Gizlilik Politikası | Aluplan Digital', description: 'Aluplan Digital gizlilik politikası.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:26:00.000Z',
        content: [],
    },
    {
        id: 'page-terms',
        title: 'Kullanım Koşulları',
        slug: '/terms',
        status: 'published',
        seo: { title: 'Kullanım Koşulları | Aluplan Digital', description: 'Aluplan Digital kullanım koşulları.' },
        authorId: 'usr-001',
        lastUpdated: '2024-07-31T10:27:00.000Z',
        content: [],
    },
];
//# sourceMappingURL=cms-data.js.map