import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCompanyKnowledgeSources1761355638337 implements MigrationInterface {
    name = 'CreateCompanyKnowledgeSources1761355638337'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_senderId"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_sessionId"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_chat_sessions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_messages_sessionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_messages_sessionId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_messages_senderType_senderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_sessionType"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_createdAt"`);
        await queryRunner.query(`CREATE TYPE "public"."company_knowledge_sources_sourcetype_enum" AS ENUM('document', 'url', 'text')`);
        await queryRunner.query(`CREATE TYPE "public"."company_knowledge_sources_status_enum" AS ENUM('pending', 'processing', 'active', 'failed', 'archived')`);
        await queryRunner.query(`CREATE TABLE "company_knowledge_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "title" character varying(500) NOT NULL, "description" text, "sourceType" "public"."company_knowledge_sources_sourcetype_enum" NOT NULL, "status" "public"."company_knowledge_sources_status_enum" NOT NULL DEFAULT 'pending', "filePath" character varying(1000), "fileName" character varying(100), "fileType" character varying(50), "fileSize" bigint, "url" character varying(2000), "lastScrapedAt" TIMESTAMP, "scrapeFailCount" integer NOT NULL DEFAULT '0', "extractedContent" text NOT NULL, "summary" text, "tags" text, "keywords" text, "metadata" jsonb NOT NULL DEFAULT '{}', "usageCount" integer NOT NULL DEFAULT '0', "helpfulCount" integer NOT NULL DEFAULT '0', "averageRelevanceScore" double precision NOT NULL DEFAULT '0', "enableForFaqLearning" boolean NOT NULL DEFAULT true, "enableForChat" boolean NOT NULL DEFAULT true, "uploadedById" uuid NOT NULL, "archivedAt" TIMESTAMP, "archivedById" uuid, CONSTRAINT "PK_e91bda92e9b848c82cfeb79002c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2f6698ca98f6c71586c23de91b" ON "company_knowledge_sources" ("uploadedById") `);
        await queryRunner.query(`CREATE INDEX "IDX_b29e79fa248189057fd5f14918" ON "company_knowledge_sources" ("sourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_986a9ed90e1971eac41d90f6ba" ON "company_knowledge_sources" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_company_knowledge_sources_tags_gin" ON "company_knowledge_sources" USING GIN (to_tsvector('english', tags))`);
        await queryRunner.query(`CREATE INDEX "IDX_company_knowledge_sources_extracted_content_gin" ON "company_knowledge_sources" USING GIN (to_tsvector('english', extracted_content))`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" DROP COLUMN "sourceType"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_context_sources_sourcetype_enum" AS ENUM('knowledge_base', 'faq_learning', 'document', 'url')`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" ADD "sourceType" "public"."chat_context_sources_sourcetype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" DROP COLUMN "relevanceScore"`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" ADD "relevanceScore" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP COLUMN "senderType"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_sendertype_enum" AS ENUM('user', 'ai', 'support')`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD "senderType" "public"."chat_messages_sendertype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP COLUMN "messageType"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_messagetype_enum" AS ENUM('text', 'file', 'url', 'system')`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD "messageType" "public"."chat_messages_messagetype_enum" NOT NULL DEFAULT 'text'`);
        await queryRunner.query(`ALTER TABLE "chat_documents" DROP COLUMN "processingStatus"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_documents_processingstatus_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`ALTER TABLE "chat_documents" ADD "processingStatus" "public"."chat_documents_processingstatus_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP COLUMN "assignmentType"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_support_assignments_assignmenttype_enum" AS ENUM('manual', 'auto', 'escalated')`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD "assignmentType" "public"."chat_support_assignments_assignmenttype_enum" NOT NULL DEFAULT 'manual'`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_support_assignments_status_enum" AS ENUM('active', 'completed', 'transferred')`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD "status" "public"."chat_support_assignments_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP COLUMN "sessionType"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_sessions_sessiontype_enum" AS ENUM('support', 'general')`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD "sessionType" "public"."chat_sessions_sessiontype_enum" NOT NULL DEFAULT 'support'`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD "status" "public"."chat_sessions_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "chat_url_cache" DROP COLUMN "processingStatus"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_url_cache_processingstatus_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`ALTER TABLE "chat_url_cache" ADD "processingStatus" "public"."chat_url_cache_processingstatus_enum" NOT NULL DEFAULT 'completed'`);
        await queryRunner.query(`CREATE INDEX "IDX_9ce433de720b1708621e1575fd" ON "chat_context_sources" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_04ff44742cbb547a5a5616f170" ON "chat_context_sources" ("relevanceScore") `);
        await queryRunner.query(`CREATE INDEX "IDX_54f62de0fc420aee902fe9b720" ON "chat_context_sources" ("sourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ce433de720b1708621e1575fd" ON "chat_context_sources" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a82476a8acdd6cd6936378cb72" ON "chat_messages" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ba4aa79109ef42c0e095c413a" ON "chat_messages" ("senderType", "senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_11ae8316dea51d14fa619e4e49" ON "chat_messages" ("sessionId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c669a59ba8d51e48176260445" ON "chat_documents" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6510a9a86527a3eaf0dbac75d6" ON "chat_documents" ("processingStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c669a59ba8d51e48176260445" ON "chat_documents" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e0bfaae0bf0b725ff75c5cc86" ON "chat_support_assignments" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_baf2cc6c6a61a892c8df361e2d" ON "chat_support_assignments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_51174b0ee2f7960654cd3852a3" ON "chat_support_assignments" ("supportUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e0bfaae0bf0b725ff75c5cc86" ON "chat_support_assignments" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0320df1059d8a029a460f4161" ON "chat_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_110c9e880fadcfb47a723669d9" ON "chat_sessions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8a950a633e01576e03f9771cf" ON "chat_sessions" ("sessionType") `);
        await queryRunner.query(`CREATE INDEX "IDX_4680547e20c7483edc930ab1c4" ON "chat_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0320df1059d8a029a460f4161" ON "chat_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_10f6a40cde71c460bddd7bc97c" ON "chat_url_cache" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7f62f1e507260c840ed0e144b6" ON "chat_url_cache" ("urlHash") `);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" ADD CONSTRAINT "FK_9ce433de720b1708621e1575fde" FOREIGN KEY ("sessionId") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" ADD CONSTRAINT "FK_43983380f956ffbb5d64468d7a6" FOREIGN KEY ("messageId") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_a82476a8acdd6cd6936378cb72d" FOREIGN KEY ("sessionId") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_fc6b58e41e9a871dacbe9077def" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_documents" ADD CONSTRAINT "FK_0c669a59ba8d51e481762604455" FOREIGN KEY ("sessionId") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_documents" ADD CONSTRAINT "FK_c78754f8973332f33fc06fec783" FOREIGN KEY ("messageId") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD CONSTRAINT "FK_4e0bfaae0bf0b725ff75c5cc861" FOREIGN KEY ("sessionId") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD CONSTRAINT "FK_51174b0ee2f7960654cd3852a31" FOREIGN KEY ("supportUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD CONSTRAINT "FK_eed1770d4420d660f4936a82803" FOREIGN KEY ("assignedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_d0320df1059d8a029a460f4161d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_knowledge_sources" ADD CONSTRAINT "FK_2f6698ca98f6c71586c23de91b4" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_knowledge_sources" ADD CONSTRAINT "FK_d6ced726997020a3027ada98209" FOREIGN KEY ("archivedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "company_knowledge_sources" DROP CONSTRAINT "FK_d6ced726997020a3027ada98209"`);
        await queryRunner.query(`ALTER TABLE "company_knowledge_sources" DROP CONSTRAINT "FK_2f6698ca98f6c71586c23de91b4"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_d0320df1059d8a029a460f4161d"`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP CONSTRAINT "FK_eed1770d4420d660f4936a82803"`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP CONSTRAINT "FK_51174b0ee2f7960654cd3852a31"`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP CONSTRAINT "FK_4e0bfaae0bf0b725ff75c5cc861"`);
        await queryRunner.query(`ALTER TABLE "chat_documents" DROP CONSTRAINT "FK_c78754f8973332f33fc06fec783"`);
        await queryRunner.query(`ALTER TABLE "chat_documents" DROP CONSTRAINT "FK_0c669a59ba8d51e481762604455"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_fc6b58e41e9a871dacbe9077def"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_a82476a8acdd6cd6936378cb72d"`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" DROP CONSTRAINT "FK_43983380f956ffbb5d64468d7a6"`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" DROP CONSTRAINT "FK_9ce433de720b1708621e1575fde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f62f1e507260c840ed0e144b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10f6a40cde71c460bddd7bc97c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0320df1059d8a029a460f4161"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4680547e20c7483edc930ab1c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8a950a633e01576e03f9771cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_110c9e880fadcfb47a723669d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0320df1059d8a029a460f4161"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e0bfaae0bf0b725ff75c5cc86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51174b0ee2f7960654cd3852a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_baf2cc6c6a61a892c8df361e2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e0bfaae0bf0b725ff75c5cc86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c669a59ba8d51e48176260445"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6510a9a86527a3eaf0dbac75d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c669a59ba8d51e48176260445"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11ae8316dea51d14fa619e4e49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ba4aa79109ef42c0e095c413a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a82476a8acdd6cd6936378cb72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ce433de720b1708621e1575fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54f62de0fc420aee902fe9b720"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04ff44742cbb547a5a5616f170"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ce433de720b1708621e1575fd"`);
        await queryRunner.query(`ALTER TABLE "chat_url_cache" DROP COLUMN "processingStatus"`);
        await queryRunner.query(`DROP TYPE "public"."chat_url_cache_processingstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_url_cache" ADD "processingStatus" character varying NOT NULL DEFAULT 'completed'`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP COLUMN "sessionType"`);
        await queryRunner.query(`DROP TYPE "public"."chat_sessions_sessiontype_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD "sessionType" character varying NOT NULL DEFAULT 'support'`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."chat_support_assignments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" DROP COLUMN "assignmentType"`);
        await queryRunner.query(`DROP TYPE "public"."chat_support_assignments_assignmenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_support_assignments" ADD "assignmentType" character varying NOT NULL DEFAULT 'manual'`);
        await queryRunner.query(`ALTER TABLE "chat_documents" DROP COLUMN "processingStatus"`);
        await queryRunner.query(`DROP TYPE "public"."chat_documents_processingstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_documents" ADD "processingStatus" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP COLUMN "messageType"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_messagetype_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD "messageType" character varying NOT NULL DEFAULT 'text'`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP COLUMN "senderType"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_sendertype_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD "senderType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" DROP COLUMN "relevanceScore"`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" ADD "relevanceScore" real NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" DROP COLUMN "sourceType"`);
        await queryRunner.query(`DROP TYPE "public"."chat_context_sources_sourcetype_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_context_sources" ADD "sourceType" character varying NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_company_knowledge_sources_extracted_content_gin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_company_knowledge_sources_tags_gin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_986a9ed90e1971eac41d90f6ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b29e79fa248189057fd5f14918"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f6698ca98f6c71586c23de91b"`);
        await queryRunner.query(`DROP TABLE "company_knowledge_sources"`);
        await queryRunner.query(`DROP TYPE "public"."company_knowledge_sources_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."company_knowledge_sources_sourcetype_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_createdAt" ON "chat_sessions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_sessionType" ON "chat_sessions" ("sessionType") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_status" ON "chat_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_userId" ON "chat_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_messages_senderType_senderId" ON "chat_messages" ("senderType", "senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_messages_sessionId_createdAt" ON "chat_messages" ("createdAt", "sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_messages_sessionId" ON "chat_messages" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_chat_sessions_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_sessionId" FOREIGN KEY ("sessionId") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_senderId" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
