import { Injectable, Logger } from '@nestjs/common';
import { MailService } from '../../mail/mail.service';
import { MailChannel } from '../../mail/interfaces/mail-service.interface';
import { User } from '../entities/user.entity';

/**
 * User Email Service
 * Handles all email notifications for user-related events
 * Pattern: Same as TicketEmailService for consistency
 */
@Injectable()
export class UserEmailService {
  private readonly logger = new Logger(UserEmailService.name);
  private readonly baseUrl: string;

  constructor(
    private readonly mailService: MailService,
  ) {
    this.baseUrl = process.env.FRONTEND_URL || process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:9003';
  }

  /**
   * Send account creation email with password reset link
   * @param user - User entity
   * @param resetToken - Password reset token (generated by caller)
   */
  async sendAccountCreatedEmail(
    user: User,
    resetToken: string,
  ): Promise<void> {
    try {
      this.logger.log(`📧 Sending account creation email to: ${user.email}`);

      const resetUrl = `${this.baseUrl}/reset-password?token=${resetToken}`;

      await this.mailService.sendMail({
        to: {
          email: user.email,
          name: `${user.firstName} ${user.lastName}`,
        },
        subject: 'Hesabınız Oluşturuldu - Şifrenizi Belirleyin',
        template: 'account-created',
        channel: MailChannel.TRANSACTIONAL,
        context: {
          userName: `${user.firstName} ${user.lastName}`,
          userEmail: user.email,
          resetPasswordUrl: resetUrl,
        },
      });

      this.logger.log(`✅ Account creation email sent successfully to: ${user.email}`);
    } catch (error) {
      this.logger.error(
        `❌ Failed to send account creation email to ${user.email}: ${error.message}`,
        error.stack,
      );
      // Don't throw - email failure shouldn't block user creation
    }
  }

  /**
   * Send password reset email
   * @param user - User entity
   * @param resetToken - Password reset token
   */
  async sendPasswordResetEmail(
    user: User,
    resetToken: string,
  ): Promise<void> {
    try {
      this.logger.log(`📧 Sending password reset email to: ${user.email}`);

      const resetUrl = `${this.baseUrl}/reset-password?token=${resetToken}`;

      await this.mailService.sendMail({
        to: {
          email: user.email,
          name: `${user.firstName} ${user.lastName}`,
        },
        subject: 'Şifre Sıfırlama Talebi',
        template: 'password-reset',
        channel: MailChannel.TRANSACTIONAL,
        context: {
          userName: `${user.firstName} ${user.lastName}`,
          userEmail: user.email,
          resetPasswordUrl: resetUrl,
        },
      });

      this.logger.log(`✅ Password reset email sent successfully to: ${user.email}`);
    } catch (error) {
      this.logger.error(
        `❌ Failed to send password reset email to ${user.email}: ${error.message}`,
        error.stack,
      );
      throw error; // Password reset should throw error if email fails
    }
  }
}
